#!/bin/bash

gpiobase=332 # edit according to your system e.g. /sys/class/gpio/gpiochip332
ice4pi_crest=$(($gpiobase+36))

#activate/zero ice_crest (MIO36)
echo ${ice4pi_crest} > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${ice4pi_crest}/direction
echo 1 > /sys/class/gpio/gpio${ice4pi_crest}/value
echo 0 > /sys/class/gpio/gpio${ice4pi_crest}/value


tr '\0' '\377' < /dev/zero | dd bs=1M count=4 of=image iflag=fullblock
dd if=${1} conv=notrunc of=image
flashrom -VVV -p linux_spi:dev=/dev/spidev0.1,spispeed=20000 -w image

echo 1 > /sys/class/gpio/gpio${ice4pi_crest}/value

