#!/bin/bash -e
gpiobase=332 # edit according to your system e.g. /sys/class/gpio/gpiochip332
ice4pi_crest=$(($gpiobase+37))

#activate/zero ice4pi_crest (MIO37)
echo $(($gpiobase+37)) > /sys/class/gpio/export || true
echo out > /sys/class/gpio/gpio${ice4pi_crest}/direction
echo 1 > /sys/class/gpio/gpio${ice4pi_crest}/value
echo 0 > /sys/class/gpio/gpio${ice4pi_crest}/value


tr '\0' '\377' < /dev/zero | dd bs=1M count=4 of=image iflag=fullblock
dd if=${1} conv=notrunc of=image
/usr/sbin/flashrom -VVV -p linux_spi:dev=/dev/spidev0.0,spispeed=20000 -w image

echo 1 > /sys/class/gpio/gpio${ice4pi_crest}/value

#CDONE
echo $(($gpiobase+45)) > /sys/class/gpio/export || true
echo in > /sys/class/gpio/gpio${ice4pi_crest}/direction || true
cat /sys/class/gpio/gpio${ice4pi_crest}/value
